# Run one of the following to run
# kubectl run alpine-sh --rm -it --image=alpine:3.16 -- sh
# kubectl run -i --rm --tty debug --image=alpine:3.16 --restart=Never -- sh
# kubectl exec pp -it -- bash
apiVersion: v1
kind: Pod
metadata:
  name: pp
spec:
  terminationGracePeriodSeconds: 0
  volumes:
  - name: cloud-amqp-secret
    secret:
      secretName: cloud-amqp-secret
      items:
      - key: .cloudampq.json
        path: cloud-amqp/.cloudampq.json
      optional: false # default setting; "mysecret" must exist
  - name: sgx-yafi-fileshare
    persistentVolumeClaim:
      claimName: generic-128mi-pvc
  containers:
  - image: python:3.7-slim
    name: python37
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: PASSWORD
    volumeMounts:
    - name: cloud-amqp-secret
      mountPath: "/mnt/secrets"
      readOnly: true
    - name: sgx-yafi-fileshare
      mountPath: /usr/share/yafi
